insert into product (category,description,name,quantity,id) values ('Book','Description Sample','Sun Tzu',10,999999)
insert into product (category,description,name,quantity,id) values ('Book','Description Sample','Cosmos',2,999998)
insert into product (category,description,name,quantity,id) values ('Book','Description Sample','1984',3,999997)
insert into product (category,description,name,quantity,id) values ('Book','Description Sample','Donnie Darko',5,999996)
insert into product (category,description,name,quantity,id) values ('Book','Description Sample','Prince of Thorns',12,999995)
insert into product (category,description,name,quantity,id) values ('Book','Description Sample','King of Thorns',14,999994)
insert into product (category,description,name,quantity,id) values ('Book','Description Sample','Animal Farm',13,999993)
insert into product (category,description,name,quantity,id) values ('Book','Description Sample','Harry Potter',1,999992)
insert into product (category,description,name,quantity,id) values ('Book','Description Sample','How to win friends and influence others',19,999991)
insert into product (category,description,name,quantity,id) values ('Book','Description Sample','General History',8,999990)